import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import DashboardLayout from "@/components/dashboardLayout/DashboardLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DashboardLayout>
              {children}
        </DashboardLayout>
      </body>
    </html>
  );
}
